repos:
- repo: local
  hooks:
    - id: rebuild-hugo
      name: Rebuild Hugo
      language: script
      entry: /bin/sh -c "HUGO_ENV=production /usr/local/bin/hugo -d docs/blog"
      files: ""
      pass_filenames: false
